### ISSUE TITLE
is crossfire support planned?

### ISSUE THREAD

**Issue by skaman82** [stronnag/LTM-lua#1]
LTM would be a very good alternative as native crossfire data is overwhelming the build in BT module and the connection is breaking up constantly

**Comment by stronnag** [comment]
Given I've had the radio for 3 days, and the extant code has only been "garden table" tested, I'd not even considered anything other than SPort telemetry. 

But sure, it's a possibility (I don't a crossfire device, but I can 'research' the code from the inav lua script).

**Comment by skaman82** [comment]
Great to hear that, thank you. Let me know if you need some help testing things. Would be also great if it could support the (optional) BT module INSIDE the radio as an alternative output source

**Comment by stronnag** [comment]
Could you please record a short OpenTX SDCard log (i.e. in /LOGS/) of a short flight with GPS telemetry. Including a number of different flight modes (e.g. Acro, PH, RTH, 3CRS, WP); don't need them all, just a few. Either post it here or PM me.

That would be a help in deciding on the required telemetry Ids needed.

**Comment by skaman82** [comment]
@stronnag just send you a sample CRSF logfile via email.

**Comment by stronnag** [comment]
It is possible that this may now work with CRSF (no promises, I don't have the hardware).

* There is a  `crsf` branch with some new code; the same code is in the attached Zip file

Unzip `ltm-lua-crsf.zip` into / copy the contents into `SCRIPTS/FUNCTIONS` such that the following directory structure is maintained; in particular `crsf.lua` is the `LTM` sub-directory:

```
├── SCRIPTS
│   ├── FUNCTIONS
│   │   ├── ltm.lua
│   │   ├── LTM
│   │   │   ├── crsf.lua
```

When the ltm.lua script is invoked (switch, telemetry event) is should recognise that CRSF is active, load the crsf.lua module and behave appropriately. If its doesn't (which is entirely probable), we can look at some debug options.

[ltm-lua-crsf.zip](https://github.com/stronnag/LTM-lua/files/4938671/ltm-lua-crsf.zip)

**Comment by mf0o** [comment]
Thanks for your great work!

I just tried the CRSF ltm.lua with some initial success. 
Setup:
 Taranis x9D+se, OpenTX 2.3 +luac, full Crossfire TX, Nano RX
 on the serial port a de-inverter, connected via two HC-05 to an u360gts tracker, running v11.1.0

Serial port is set to LUA, script will be engaged through a switch.
On the u360gts I've set telemetry to LTM with 115200 baud.

I do receive coordinates and altitude but update rate will be shown 0Hz in the u360gts. Using a cable connection between the x9D and the u360gts will get me 5Hz.

cheers :)

**Comment by stronnag** [comment]
Thanks for the confirmation. 

* The script knows nothing about the physical transport; possibly the HC-05 drop some data at 115200. 
* The script does nothing to configure the UART in any way, so it uses whatever OpenTX provides. 
* I think I get about 5Hz using a JDY-31 BT into a laptop with mwp.

Time to merge this into the master branch.

**Comment by skaman82** [comment]
thank you @stronnag for this!

**Comment by stronnag** [comment]
let's close this, as we at least pass the 'planned' hurdle.

**Comment by mf0o** [comment]
short headsup:
I did some tests and disabled the a-, s- and x- frames in the man "run" function. Now I get 5Hz via Bluetooth as well.
Have to reproduce the 0Hz "issue" first, and second need to check what counters are used by the u360gts.

Dont know if a "tracker-mode" option would be accepted by you or if this will remain a workaround for u360gts users.

**Comment by stronnag** [comment]
Please create a new issue along the lines of "Tracker / GPS only" option and I'll address it.
If you only need gframe and occassional oframe, then you should get c. 10Hz updates.
