### ISSUE TITLE
cannot get telemetry on TX16s on EdgeTX 2.7.1

### ISSUE THREAD

**Issue by jiri-jirus** [stronnag/LTM-lua#10]
hello, i cannot get LTM telemetry out from my radiomaster tx16s.
-have set global function for proper switch to LTM lua script.
-have set aux as LUA in system menu/hardware
-other lua scripts that output information on AUX works
-when aux set as telemetry mirror, i got CRSF telemetry.

thanks for help

running
edgetx 2.7.1
TBS Crossfire 6.19
iNav 5.1.0

log file in attachment
[CRSF-2022-10-05-174436.csv](https://github.com/stronnag/LTM-lua/files/9717548/CRSF-2022-10-05-174436.csv)

**Comment by stronnag** [comment]
* The results of #7 / #9 / v0.0.4 demonstrate that the script **does** work with CRSF on TX16S
* Replaying your log snippet in Companion 2.7(.1) results in valid LTM being generated
* Replaying a more substantive CRSF log in Companion 2.7(.1) results in valid LTM being generated
* Valid LTM can be captured from a serial port (using Sport, all I can test).

So there is nothing more I can do, in particular #7 / #9 https://github.com/stronnag/LTM-lua/issues/7#issuecomment-1270078517 demonstrates that serial LTM can be generated from CRSF.

**Comment by jiri-jirus** [comment]
in my simulator, your script failed with: 

`-E- FUNCTIONS/ltm.lua:349: attempt to index upvalue 'S' (a function value)`

**Comment by stronnag** [comment]
Huum, line 348 probably wants its brackets back ...

```
   S = loadScript("/SCRIPTS/FUNCTIONS/LTM/config.lua")()
```

**Comment by stronnag** [comment]
AFAIK, in order to use a CRSF log replay, it is necessary to uncomment line 356 as well.
```
   if D.sim then D.fm_id = 1 end
```

**Comment by jiri-jirus** [comment]
> AFAIK, in order to use a CRSF log replay, it is necessary to uncomment line 356 as well.
> 
> ```
>    if D.sim then D.fm_id = 1 end
> ```

I dont need to use CRSF log replay. I just would like the script to compile.
