### ISSUE TITLE
Internal BT support

### ISSUE THREAD

**Issue by skaman82** [stronnag/LTM-lua#3]
Is it possible to add an option to send LTM data via internal BT module of the radio (x-lite, horus, radiomaster) instead through serial port pins?

**Comment by stronnag** [comment]
If you point me to some OpenTX documentation that describes how this works ..... in particular how it's exposed via a LUA API.

**Comment by skaman82** [comment]
@stronnag I don't know either - but will try to find out

**Comment by stronnag** [comment]
Thanks, the OTX documentation is a bit weak / out of date in the whole UART area; otoh it's quite new and writing API documentation is not universally popular.

**Comment by skaman82** [comment]
doesn't look good I'm afraid: https://github.com/opentx/opentx/issues/7835

**Comment by stronnag** [comment]
Thanks for asking. I'll close this for now, please reopen if OTX gains an API.
