### ISSUE TITLE
Tracker only mode

### ISSUE THREAD

**Issue by skaman82** [stronnag/LTM-lua#4]
To achieve higher update rates for antenna tracking - we could skip most of the frames (only sat count, LAT/LONG and alt needed)

**Comment by stronnag** [comment]
OK, as there is no UI for function scripts, it will 'simply' involve a small edit to `ltm.lua` (once I publish it, probably 2020-07-21, it's an easy update).

```
-- Functionality
-- If you're just using this for an antenna tracker (vice GCS), then you probably don't
-- need the A,S and X frames. So change the line below from
--
-- local onlyTracker = false
--  to
-- local onlyTracker = true
--

local onlyTracker = false
```

I guess you don't need to O-frame (Origin/Home), as the tracker has its own GPS? If so, I'll also disable sending that in tracker mode.

This should give you c. 10Hz GPS updates (which is an arbitrary limitation in the script to keep the processing load low).

**Comment by skaman82** [comment]
@stronnag sounds good. Yes, the O-frame is not needed as the tracker uses either its own GPS or a button press to store the home point from the aircraft in front of it prior launch.

**Comment by stronnag** [comment]
OK, I'll publish a beta branch tomorrow.

**Comment by mf0o** [comment]
Did a quick dig into the u360gts code. They do parse A-, G-, S- O-frames but on the tracker only G and A frames seem to be used.
telemetry_course for example is obtained from the A frame, which is used on the position estimator. Guess EPS wont work without A frames. Maybe there is even more impact.

I can do some tests later with only the G frame active, not sure how to test EPS correctly with a G-frame-only-ltm-lua.

**Comment by stronnag** [comment]
There's now a `gps-tracker-only` branch, contents in the Zip file attached.
The settings are in `LTM/config.lua` (to make it less likely that a user edit breaks the whole thing and for future flexibility). 

Just change the line
```
S.onlyTracker = false
```
to
```
S.onlyTracker = true
```
then there will only be G and A frames transmitted. Note: The default is all LTM frames.

[ltm-lua-issue_4.zip](https://github.com/stronnag/LTM-lua/files/4953881/ltm-lua-issue_4.zip)

**Comment by skaman82** [comment]
yes, this is a good solution and it is working as intended. But I am still getting max 5Hz rate. Even 4Hz when running INAV telemetry script in my TX16S in parallel. Will test fly this with the tracker tomorrow.

**Comment by stronnag** [comment]
You will only get 5Hz for a single "entity", the output alternates between G and A frames at 0.1s intervals. There's no reason (other than rate limiting) not to send both at 0.1s. As you've noticed, OpenTX manages lua resource usage (globally), so the more scripts you have running, the slower it will be.

The attached variation sends both G and A frames at nominally 0.1s interval. 

Decide which you prefer, and I'll commit that one.
[ltm-lua-issue_4a.zip](https://github.com/stronnag/LTM-lua/files/4994572/ltm-lua-issue_4a.zip)

**Comment by mf0o** [comment]
I tried this and get 10Hz when the tracker mode is enabled, with trackermode false it will be 5Hz.

Great work!

**Comment by stronnag** [comment]
Thanks, I'll merge it later.

**Comment by stronnag** [comment]
Merged
