### ISSUE TITLE
Some data are missing

### ISSUE THREAD

**Issue by Alienix33** [stronnag/LTM-lua#6]
Hi, I am using LTM.lua script on my TX16S ( telemetry send by onboard X8R receiver and SPORT connected to FC).
On LTM messages output from TX16S uart:
-  following are ok: Lat, Long, RSSI, VBat
-  but numsats and fix  remains at 0 (note  roll, pitch and heading also)
As LTM messages are used by an antenna tracker, numsats and fix data are very important please can you check what is wrong

**Comment by stronnag** [comment]
> * please can you check what is wrong

Not without you providing some basic  information.

* Version of OpenTX / EdgeTX
* have you set the `S.onlyTracker` setting ?
* Please capture the output LTM, preferably using [mwp-serial-cap](https://github.com/stronnag/mwptools/tree/master/src/samples/mwp-serial-cap)

**Comment by Alienix33** [comment]
- I am using OpenTX 2.3.14
- Yes I have set S.onlyTracker and into the script I have added the S frame,  I am using G, A & S frames.
- see here attached my Yaapu telemetry screen is working very well wheer  all received data are displayed with GPS position and 8 sats, then on a switch command I launch LTM.lua, see here attached hexa capture (sorry I am not familar with mwp-serial-cap)

[capture-2021-12-15.txt](https://github.com/stronnag/LTM-lua/files/7720193/capture-2021-12-15.txt)
![screen-2021-12-15-161247](https://user-images.githubusercontent.com/86925151/146204632-5e1cc5e2-a028-459a-861b-9490708dcffb.jpg)
![screen-2021-12-15-161632](https://user-images.githubusercontent.com/86925151/146204664-75804a6c-1c6f-4774-8644-a174fdedf01c.jpg)
)

**Comment by stronnag** [comment]
> * I am using OpenTX 2.3.14
> * Yes I have set S.onlyTracker and into the script I have added the S frame,  I am using G, A & S frames.

So you've modified the script.Guees what, it works fine if you don't.

> * (sorry I am not familar with mwp-serial-cap)

And I'm not familiar with either Yappu or whatever other tools you've used.

No fault found. Works for me.

**Comment by Alienix33** [comment]
I provided picture of my yahoo screen only to show that my TX16S is
receiving all GPS data from FrSky telemetry.
LTM.lua works partially as some data are correctly transferred like Lat,
Long, RSSI, VBat  and some other remains filled with zero like roll pitch,
numsats. Refer my record (attached TXT file)
without my modification to introduce the S frame into the S.onlytracker it
is the same
My question is what can I do to get at minimum numsats correctly ?

regards

Le mer. 15 déc. 2021 à 16:05, Jonathan Hudson ***@***.***> a
écrit :

**Comment by stronnag** [comment]
1. LTM-lua provides the documented data. If you want S-frames, set `S.onlytracker` to false
2. Please use the tool requested if you wish me to look at anything. I have better things to do than transform your file into something I can use.

**Comment by stronnag** [comment]
You didn't say which version of inav you're using on the FC ... or maybe you're not. In which case you won't get the status data as it's encoding is FC specific.

**Comment by Alienix33** [comment]
I am using arduplane 4.1.4 on a h743 matek fc connected to X8R receiver via
sport and frsky passthru

Le mer. 15 déc. 2021 à 20:56, Jonathan Hudson ***@***.***> a
écrit :

**Comment by stronnag** [comment]
> I am using arduplane 4.1.4 on a h743 matek fc connected to X8R receiver via sport and frsky passthru

Then you'd need to decode however ardupilot encodes the missing status fields. Or provide a TX telemetry log and a description of how it's done (or link to such a description). Then it could be handled in a similar way to CRSF from inav.

**Comment by stronnag** [comment]
Unpleasant feeling of [deja vu](https://github.com/stronnag/bbl2kml/issues/13) approaching.
